# Generated by Django 4.0.4 on 2022-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_banku', models.CharField(max_length=60)),
                ('sesja_przych1', models.TimeField()),
                ('sesja_przych2', models.TimeField()),
                ('sesja_przych3', models.TimeField()),
                ('sesja_wych1', models.TimeField()),
                ('sesja_wych2', models.TimeField()),
                ('sesja_wych3', models.TimeField()),
            ],
        ),
    ]
