# Generated by Django 4.0.4 on 2022-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblicz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='sesja_przych1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='sesja_przych2',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='sesja_wych1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='sesja_wych2',
            field=models.TimeField(null=True),
        ),
    ]
